/**
 * Canonical protocol docs — the site serves the FULL Standards Architecture
 * documents, sourced from committed derived copies in content/canon/
 * (regenerated by `npm run sync-canon`; drift caught by canon-sync.test.ts).
 *
 * Server-only: reads from the filesystem at build/render time. Client
 * components must not import this module (navigation and other client-safe
 * data stay in demo.ts).
 *
 * Loader behavior (presentation, not editing — the derived copies stay
 * verbatim): strips the generated provenance header (surfaced instead as
 * sourcePath/sourceSha), the YAML frontmatter, the document's own `# Title`
 * (the masthead already speaks it), and — only when it duplicates the
 * masthead subtitle — the opening italic epigraph.
 */

import fs from "node:fs";
import path from "node:path";
import type { ProtocolDoc } from "./schema";

const CANON_DIR = path.join(process.cwd(), "content", "canon");

const HEADER_RE =
  /^<!-- DERIVED COPY — do not edit\. Source: (\S+) @ (\S+)\. Regenerate: npm run sync-canon -->\n/;

interface CanonDocMeta {
  slug: string;
  title: string;
  subtitle: string;
  category: ProtocolDoc["category"];
  order: number;
}

const canonDocMeta: CanonDocMeta[] = [
  {
    slug: "cultural-physics",
    title: "The Theory of Cultural Physics",
    subtitle:
      "A framework for designing across systems of creativity and culture",
    category: "theory",
    order: 1,
  },
  {
    slug: "coherence-design",
    title: "Coherence Design",
    subtitle:
      "The discipline of designing systems that hold their shape across time, scale, and transmission",
    category: "discipline",
    order: 2,
  },
  {
    slug: "coherence-operating-system",
    title: "The Coherence Operating System",
    subtitle:
      "Maintaining structural alignment inside systems that would otherwise fracture under pressure",
    category: "practice",
    order: 3,
  },
  {
    slug: "constitution",
    title: "The Constitution of Facework",
    subtitle:
      "The governing boundaries that keep the practice aligned when conditions change",
    category: "practice",
    order: 4,
  },
  {
    slug: "protocol-v1",
    title: "Facework Protocol",
    subtitle:
      "An open standard for turning cultural signal into coherent, ownable business systems",
    category: "practice",
    order: 5,
  },
  {
    slug: "build-methodology",
    title: "Build Methodology",
    subtitle: "From idea to handoff-ready architecture: the GAMUT case study",
    category: "practice",
    order: 6,
  },
  {
    slug: "conformance-model",
    title: "Conformance Model",
    subtitle:
      "What 'Facework Protocol Conformant' means — and how it's verified",
    category: "governance",
    order: 7,
  },
  {
    slug: "standards-track",
    title: "Standards Track",
    subtitle:
      "How formal standards fit into the system, and why that layer is intentionally deferred",
    category: "governance",
    order: 8,
  },
];

/** Normalize for the subtitle-vs-epigraph duplicate check. */
function normalize(text: string): string {
  return text
    .replace(/[*™]/g, "")
    .replace(/\s+/g, " ")
    .replace(/\.$/, "")
    .trim()
    .toLowerCase();
}

function loadCanonDoc(meta: CanonDocMeta): ProtocolDoc {
  const raw = fs.readFileSync(path.join(CANON_DIR, `${meta.slug}.md`), "utf8");

  const headerMatch = raw.match(HEADER_RE);
  if (!headerMatch) {
    throw new Error(
      `content/canon/${meta.slug}.md is missing its DERIVED COPY header — run: npm run sync-canon`
    );
  }
  const [, sourcePath, sourceSha] = headerMatch;
  let body = raw.slice(headerMatch[0].length);

  // YAML frontmatter — stripped from the body, but the status the source
  // declares for itself is kept and surfaced verbatim on the doc page
  // (honesty: a Working Draft must read as a Working Draft).
  let sourceStatus: string | undefined;
  const frontmatter = body.match(/^---\n([\s\S]*?)\n---\n/);
  if (frontmatter) {
    const statusLine = frontmatter[1].match(/^status:\s*(?:"([^"]*)"|(.+))$/im);
    if (statusLine) sourceStatus = (statusLine[1] ?? statusLine[2]).trim();
    body = body.slice(frontmatter[0].length);
  }

  // The document's own H1 — the masthead already renders the title.
  body = body.replace(/^\s*# .*\n/, "");

  // Opening italic epigraph, only when it duplicates the masthead subtitle.
  const lines = body.split("\n");
  let i = 0;
  while (i < lines.length && lines[i].trim() === "") i++;
  if (lines[i]?.startsWith("*") && !lines[i].startsWith("**")) {
    let j = i;
    let epigraph = "";
    while (j < lines.length && lines[j].trim() !== "") {
      epigraph += (epigraph ? " " : "") + lines[j].trim();
      j++;
    }
    if (epigraph.endsWith("*") && normalize(epigraph) === normalize(meta.subtitle)) {
      lines.splice(i, j - i);
    }
  }
  body = lines.join("\n");

  // Leading blank lines / horizontal rules read as dead space under the
  // masthead — trim until real content starts.
  body = body.replace(/^(\s*\n|---\n)+/, "");

  return { ...meta, content: body.trimEnd(), sourcePath, sourceSha, sourceStatus };
}

export const protocolDocs: ProtocolDoc[] = canonDocMeta.map(loadCanonDoc);
